version: "3.9"
services:
  fpl-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /volume1/docker/fpl-optimization/data:/app/data
    # restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    # No 'command' needed here. We'll use docker exec.