version: "3.9"
services:
  fpl-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /volume1/docker/fpl-optimization/data:/app/data
    # restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    stdin_open: true  # Add this line
    tty: true        # Add this line