version: "3.9"
services:
  fpl-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:  <-- Remove or comment out the ports section
    #   - "8088:8000"
    volumes:
      - /volume1/docker/fpl-optimization/data:/app/data
    # restart: unless-stopped  # This is still useful
    environment:
      - PYTHONPATH=/app
    command: python solve_regular.py # Add command section.