version: '3'

services:
  app:
    build: .
    container_name: fpl_optimization_tools
    volumes:
      - /volume1/docker/fpl-optimization/output:/fpl-optimization/run/data
    stdin_open: true
    tty: true